name: Python Register

on:
    issue_comment:
        types: created
    watch:
        types: started
    schedule:
    - cron: '*/30 20-15 * * *'

jobs:
  bot:
    environment: EMAIL_CONFIG
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
        
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push 
      
      - name: '安装Python环境'
        uses: 'actions/setup-python@v3'
        with: 
            python-version: 3.9
            cache: 'pip' # caching pip dependencies
        
      - name: "配置依赖"
        run: pip install -r requirements.txt
        #run: pip install requests

      - name: "获取北京时间"
        run: bash ./00.LinuxShell/action_log.sh
      #- name: 'Send filelist mail using 163'
       # uses: dawidd6/action-send-mail@v3.6.1
        #with:
         # server_address: smtp.163.com
          #server_port: 465
          #username: ${{ secrets.EMAIL_163_USER_NAME }}
          #password: ${{ secrets.EMAIL_163_USER_PWD }}
          #subject: the file list about the compile
          #body: Github Action Send File List
          #html_body: file://email_content.txt
          #html_body: file://123456.txt
          #to: tp232fs234@chacuo.net
          #to: ${{ secrets.EMAIL_ADDRESS_FOR_NOTIFY }}
          #from: ${{ secrets.EMAIL_SEND_NAME }}
      #- name: "数据抓取测试"
      #  run: python3 ./01.Python/test.py
      - name: "Python Register"
        env:
            EMAIL_SMTP_DOMAIN: ${{ secrets.EMAIL_SMTP_DOMAIN }}
            EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
            EMAIL_SMTP_REV: ${{ secrets.EMAIL_ADDRESS_FOR_NOTIFY }}
            EMAIL_SMTP_USER_NAME: ${{ secrets.EMAIL_SMTP_USER_NAME }}
            EMAIL_SMTP_USER_PWD: ${{ secrets.EMAIL_SMTP_USER_PWD }}
            FILE_ENCRYPT_DECRYPT_KEY: ${{ secrets.FILE_ENCRYPT_DECRYPT_KEY }}
        run: python3 ./01.Python/PackedScript.py continue_crawler.py
    
      - name: "Commit & Push changes"
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PUSH_KEY }}
          author_email: "tp_proton_aly@protonmail.com"
          author_name: "tpa"
    
     
