name: 天气预报

on: 
    schedule:
    - cron: '45 22 * * *'
    #- cron: '25 7 * * *'

jobs:
  bot:
    environment: EMAIL_CONFIG
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      
      - name: '安装Python环境'
        uses: 'actions/setup-python@v3'
        with: 
            python-version: 3.9
        
      - name: "配置依赖"
        run: pip install -r requirements.txt
        #run: pip install requests

      #- name: '生成当前文件列表'
       # run: bash ./00.LinuxShell/action_log.sh
      #- name: 'Send filelist mail using 163'
       # uses: dawidd6/action-send-mail@v3.6.1
        #with:
         # server_address: smtp.163.com
          #server_port: 465
          #username: ${{ secrets.EMAIL_163_USER_NAME }}
          #password: ${{ secrets.EMAIL_163_USER_PWD }}
          #subject: the file list about the compile
          #body: Github Action Send File List
          #html_body: file://email_content.txt
          #html_body: file://123456.txt
          #to: tp232fs234@chacuo.net
          #to: ${{ secrets.EMAIL_ADDRESS_FOR_NOTIFY }}
          #from: ${{ secrets.EMAIL_SEND_NAME }}
      #- name: "数据抓取测试"
      #  run: python3 ./01.Python/test.py
      - name: "Python Send EMail To Sis"
        env:
            EMAIL_SMTP_DOMAIN: ${{ secrets.EMAIL_SMTP_DOMAIN }}
            EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
            EMAIL_SMTP_REV: ${{ secrets.EMAIL_SIS_RECV_ADDR }}
            EMAIL_SMTP_USER_NAME: ${{ secrets.EMAIL_SMTP_USER_NAME }}
            EMAIL_SMTP_USER_PWD: ${{ secrets.EMAIL_SMTP_USER_PWD }}
        run: python3 ./01.Python/send_to_sis.py
    
     
